# Generated by Django 4.0.3 on 2022-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked',
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('R', 'Received'), ('S', 'Sent')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
