# Generated by Django 4.0.3 on 2022-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_customer_managers_alter_supplier_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
