version: "3.7"

services:

  django_web:
    build: .
    command: >
      ash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
volumes:
  postgres_data: